### ISSUE TITLE
assertRedirect assumes that the status code is 301 or 302

### ISSUE THREAD

**Issue by treadup** [jarus/flask-testing#101]
The assertRedirect function assumes that the status code for a redirect is 301 or 302. This is too restrictive. 

According to the [flask.redirect](http://flask.pocoo.org/docs/0.12/api/#flask.redirect) documentation the supported status codes are 301, 302, 303, 305, and 307. 

I ran into this issue when I was trying to test a 303 redirect.

**Comment by jcomo** [comment]
Agreed! Good callout. Feel free to submit a PR

**Comment by treadup** [comment]
Will do. Should have a PR by this weekend.
