### ISSUE TITLE
if some fail in teardown could be trigger _post_teardown error

### ISSUE THREAD

**Issue by dreampuf** [jarus/flask-testing#21]
I custome my TestCase's teardown method, and it case a error. 
When I run this case, it could raise a error about Flask-testing's `self._ctx.pop()` error ([link](https://github.com/jarus/flask-testing/blob/master/flask_testing/utils.py#L112)) .
That make me can't find real problem except I note r85 .

When the teardown method raise a error, flask-testing execute the _post_teardown will case this error :

``` python
AssertionError: Popped wrong request context.  (<RequestContext 'http://localhost/connect/signup' [POST] of run> instead of <RequestContext 'http://localhost/' [GET] of run>)
```

**Comment by tkannippoyil** [comment]
@eriktaubeneck :100:   worked... :)

**Comment by rlam3** [comment]
+1 this is still failing even with PRESERVE_CONTEXT_ON_EXCEPTION = False

**Comment by shankeygr** [comment]
PRESERVE_CONTEXT_ON_EXCEPTION = False, is not working for me

**Comment by xavierhardy** [comment]
`PRESERVE_CONTEXT_ON_EXCEPTION` set to `False` exceptions in the mock Flask client are re-raised in the testing context which is not the behavior we want. We want to check the output our user sees (for example, a bad request status code).

**Comment by xavierhardy** [comment]
I found what was causing the error in my case, the error handler itself had an error (which hasn't been raised).

**Comment by dreampuf** [comment]
I used flask-testing years ago. This feature doesn't need anymore. 
Feel free to re-open this, if you has the same issue.

**Comment by dasfrosty** [comment]
This is still an issue in the latest version of flask-testing (v0.6.2).

Setting `PRESERVE_CONTEXT_ON_EXCEPTION = False` does work to solve the issue though.

**Comment by dasfrosty** [comment]
Just to add some clarity, the `AssertionError: Popped wrong request context` error only happens when running the tests with the flask debug flag turned on.

This is because, from the flask config docs (http://flask.pocoo.org/docs/0.12/config/)...
```
By default if the application is in debug mode 
the request context is not popped on exceptions 
to enable debuggers to introspect the data.
```

So the other way to avoid this issue is to turn the debug flag off for testing:
```
export FLASK_DEBUG=0
```

**Comment by zoltan-fedor** [comment]
I started to receive the same errors too and none of the above suggestions has helped, not the `PRESERVE_CONTEXT_ON_EXCEPTION = False` nor the `DEBUG` flag being set to `0`.

What did help in my case is turning off shared fixtures (`scope="session"`) in pytest and setting their scope to `function`, which is the default.

This way my test runs became a bit less efficient, but now at least they don't error out randomly with the above error.

**Comment by harshal-c** [comment]
I'm still facing this issue when I try to test background tasks using python-rq and have come across the same issue of `AssertionError: Popped wrong request context.`. I have applied all the suggested options still no good. Below are the fixtures which I use. Would appreciate if anyone can help with this. 

I'm on python3.8 and using flask 2.0

P.S setting fixture scope to default also doesn't help the case

```
@pytest.fixture(scope='session')
def app():
    _app = create_app()
    _app.config["TESTING"] = True
    _app.config["PRESERVE_CONTEXT_ON_EXCEPTION"] = False
    _app.config["FLASK_DEBUG"] = False

    _app.test_request_context().push()

    yield _app


@pytest.fixture(scope='session')
def api(app):

    with app.test_client() as testing_client:
        _db.init_app(app)
        _db.create_all()

        yield testing_client
    
    _db.session.close()
    _db.drop_all()
    _db.get_engine(_db.app).dispose()

@pytest.fixture(scope='session')
def redis_worker(app, api):
    """Redis worker for processing jobs """

    queue = Queue(connection=Redis('127.0.0.1', 6300))
    return  SimpleWorker([queue], connection=queue.connection)

```

**Comment by jonasN5** [comment]
> What did help in my case is turning off shared fixtures (scope="session") in pytest and setting their scope to function, which is the default.

This is the only thing that worked for me. Looking for the efficient way by preserving the session scope...
