### ISSUE TITLE
How do I test render_template()

### ISSUE THREAD

**Issue by nueverest** [jarus/flask-testing#54]
How do I test this line? 
`return render_template(u'http_error.html', error_detail=detail)`

I am a beginner as far as flask testing is concerned.

There is an unanswered question similar to this on stackoverflow.
http://stackoverflow.com/questions/23987564/test-flask-render-template-context

**Comment by jcomo** [comment]
@neuverest was that able to solve your issue?

**Comment by nueverest** [comment]
yes
