### ISSUE TITLE
Support for mongodb testing

### ISSUE THREAD

**Issue by sri85** [jarus/flask-testing#81]
Can we use mongodb instead of SQL? Does the framework support mongodb?

**Comment by jcomo** [comment]
We don't have specific support for SQLAlchemy - the framework is agnostic towards the choice of backend. There is some explanation for how to use SQLAlchemy in combination with this framework in the docs, but it's by no means the only database you can use. Mongodb will work just as well although the code to set it up in a test case will look different.
