### ISSUE TITLE
db.create_all() in LiveServerTestCase

### ISSUE THREAD

**Issue by PiscesDream** [jarus/flask-testing#86]
In *Testing with SQLAlchemy* section of the document:

```
def setUp(self):
        db.create_all()
```
will cause error `RuntimeError: application not registered on db instance and no application bound to current context` with class `LiveServerTestCase`

which can be fixed by:
```
def setUp(self):
    with self.app.app_context():
        db.create_all()
```

**Comment by danwiesenthal** [comment]
I see the same behavior.  I don't know if it's intended or not, but I find it inconsistent (and therefore confusing) with the flask_testing.TestCase behavior, where it appears that an app_context is created/pushed before setUp.

**Comment by jcomo** [comment]
What version of flask-testing are you using? I just made a quick sample app that works fine without needing the app_context contextmanager

```python
# app.py

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'
db = SQLAlchemy(app)


@app.route('/')
def hello():
    return 'hello world'
```

```python
# test_app.py

from unittest import main
from flask_testing import LiveServerTestCase

import requests

from app import app, db


class AppTestCase(LiveServerTestCase):
    def create_app(self):
        return app

    def setUp(self):
        print 'creating the db'
        db.create_all()

    def test_route(self):
        response = requests.get(self.get_server_url())
        self.assertEqual(200, response.status_code)


if __name__ == '__main__':
    main()
```

**Comment by danwiesenthal** [comment]
I'm using Flask-Testing 0.4.2

**Comment by jcomo** [comment]
Could you provide more code for the example you're talking about? Like I mentioned, I cant reproduce the issue with a simple example

**Comment by jcomo** [comment]
A new version (0.5.0) has been released to PyPI that should include a fix to this issue. Please reopen if you upgrade the library and continue to see it
