### ISSUE TITLE
Update PyPI Version

### ISSUE THREAD

**Issue by techguy613** [jarus/flask-testing#90]
Can you please update the available version in PyPI? The last update was done in 2014 and there are some major fixes. I'm totally ok using a nasty-looking line in requirements.txt, but Flask-Testing==0.5.0 or 0.4.3 would be really nice :)

Thanks all!

**Comment by jcomo** [comment]
Absolutely! Didn't realize it had been so long since the last update. I'm relatively new as a collaborator and don't have access to the package on pypi, but I'll see what I can do. Stay tuned

**Comment by techguy613** [comment]
Thanks @jcomo 👍

**Comment by jcomo** [comment]
Sorry, it took a little longer than expected but v0.5.0 has been released. Go fix up those requirements.txt's :)
